format = """
[ ](#FFFFFF)\
[> ](bold green)\
$username[@](#9a348e)$hostname\
$directory\
$git_branch(#FCA17D)\
$git_status(#FCA17D)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$time
[󱞩 ](bold green)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[hostname]
ssh_only = false
format = "[$hostname ](#9a348e)"
disabled = false

[username]
show_always = true
style_user = "#9A348E"
style_root = "#9A348E"
format = '[$user]($style)'
disabled = false

[directory]
style = "#DA627D"
format = "[ /$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "#33658A"
format = '[  $time ]($style)'
