# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs-unstable, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "btusb" "btintel" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
   # universal-pidff
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2e831617-96db-4831-b74a-db466cc6f111";
      fsType = "btrfs";
      options = ["noatime" "ssd" "space_cache=v2" "defaults"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6C01-2C33";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/Games" =
    { device = "/dev/disk/by-uuid/a7a23c57-8e83-4f9c-a886-4f15caf27669";
      fsType = "ext4";
    };

  fileSystems."/mnt/NewGames" =
    { device = "/dev/disk/by-uuid/ebc712b6-2a9a-45e7-b009-ed3787f19cae";
      fsType = "ext4";
    };

  swapDevices = [ {
    device = "/mnt/NewGames/.swapfile";
    size = 18*1024;
  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
